name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    name: Build & Release & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@riccox/colorify"
          pull-request-title-pattern: "chore(release): v${version}"

      - name: Echo status of release-please
        env:
          RELEASES_CREATED: ${{ steps.release.outputs.releases_created }}
          RELEASE_CREATED: ${{ steps.release.outputs.release_created }}
        run: |
          echo "releases_created: $RELEASES_CREATED"
          echo "release_created: $RELEASE_CREATED"

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - name: Setup PNPM
        if: ${{ steps.release.outputs.releases_created }}
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.1

      - name: Install deps
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm install

      - name: Build
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm run build

      - name: Publish
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}